apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi 
  namespace: api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryvhd1032.azurecr.io/tripinsights/poi:latest
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminvHd1032"
        - name: SQL_SERVER
          value: "sqlservervhd1032.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        volumeMounts:
        - name: SQL_PASSWORD
          mountPath: /secrets
          readonly: true
      volumes:
        - name: SQL_PASSWORD
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure"
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: SQL-Password
      nodeSelector:    
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: poi