apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "false"    # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: "c2efb702-55d6-46d9-b602-c79b362c3acc"     # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "tripinsights" # the name of the KeyVault
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: SQL-Password
          objectType: secret       
    resourceGroup: "teamResources"     # [REQUIRED] the resource group name of the key vault
    subscriptionId: "1f33d63d-b8e4-481b-bee6-a58430a90be8"          # [REQUIRED] the subscription ID of the key vault
    tenantId: "1c7b6fb5-dc28-4eb7-ab39-361ce6de20b1"