apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripsapi 
  namespace: api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripsapi
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: tripsapi
    spec:
      containers:
      - name: tripsapi
        image: registryvhd1032.azurecr.io/tripinsights/trips:latest
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminvHd1032"
        - name: SQL_SERVER
          value: "sqlservervhd1032.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        volumeMounts:
        - name: sql-password
          mountPath: /secrets
          readOnly: true
      volumes:
        - name: sql-password
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "tripsinsightssec"
      nodeSelector:    
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: tripsapi
  namespace: api 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: tripsapi
