apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile 
  namespace: api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryvhd1032.azurecr.io/tripinsights/userprofile:latest
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminvHd1032"
        - name: SQL_PASSWORD
          value: "mJ2tq2Zw2"
        - name: SQL_SERVER
          value: "sqlservervhd1032.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
      nodeSelector:    
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: userprofile
